[project]
name = "websockets-broadcaster"
version = "0.1.0"
description = "WebSockets Broadcaster"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-fasthtml>=0.6.4",
    "reactivex>=4.0.4",
]
